project:
  type: website

website:
  title: "ctompkins_quarto_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/conorotompkins
      - icon: linkedin
        href: www.linkedin.com/in/conor-tompkins-04b06a3b
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

